export type PlayerRole =
  | "Entry"
  | "Fragger"
  | "Support"
  | "Awper"
  | "Lurker"
  | "Rifler";

export type PlayerStats = {
  steamId: string;
  team: string;
  name: string;
  role: PlayerRole;
  gamesPlayed: number;
  rating: number;
  kpr: number;
  adr: number;
  kast: number;
  odr: number;
  impact: number;
  ctRating: number;
  tRating: number;
  adp: number;
  utilDamage: number;
  enemiesFlashed: number;
  flashAssists: number;
  utilThrown: number;
  headshotPercent: number;
  awpPR: number;
  multiPR: number;
  clutchPR: number;
  suppRounds: number;
  suppDmgPR: number;
  odaPR: number;
  entriesPR: number;
  tradesPR: number;
  tradeRatio: number;
  savesPR: number;
  saveRate: number;
  twoKs: number;
  threeKs: number;
  fourKs: number;
  aces: number;
  rounds: number;
  peak: number;
  pit: number;
  form: number;
  consistency: number;
  kills: number;
  assists: number;
  deaths: number;
  mipPR: number;
  impactOnWin: number;
  kpa: number;
  rwk: number;
  dmgDiff: number;
  entryAttemptsPR: number;
  averageDeathTime: number;
  ctAdp: number;
  tAdp: number;
  eFF: number;
  enemyBlindTime: number;
  dmgPerNade: number;
  ctAwp: number;
  ctKillsPR: number;
  lurks: number;
  wonLurks: number;
};
